[lint]
ignore = ["implicit_assignment", "duplicated_arguments"]
exclude = ["tests/testthat/test_ci/*"]
extend-select = ["TESTTHAT", "DPLYR", "unnecessary_nesting", "nzchar", "quotes"]
check-roxygen = true
fix-roxygen = true

[lint.assignment]
operator = "<-"

[lint.quotes]
quote = "double"
