---
title: "Licenses on R packages"
author: "Diego Hernangómez"
date: "`r Sys.Date()`"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  tidy = "styler",
  warning = FALSE,
  message = FALSE,
  dpi = 150,
  dev = "ragg_png",
  fig.path = "./",
  out.width = "100%"
)

```

Precompute

```{r setup}
library(cffr)
```

```{r}

# Enable CRAN
options(repos = c(
  CRAN = "https://cloud.r-project.org"
))

library(tidyverse)

cran_packages <- available.packages()[, "License"] %>%
  table(dnn = "cran_licenses") %>%
  as.data.frame(responseName = "n") %>%
  as_tibble() %>%
  arrange(desc(n))

# Manipulate some fields
cran_packages$cran_licenses <- factor(cran_packages$cran_licenses,
  levels = cran_packages$cran_licenses
)
cran_packages$rank <- c(1:nrow(cran_packages))

cran_packages$cum <- cumsum(cran_packages$n) / sum(cran_packages$n)

cran_packages
```

```{r dist}

n_975 <- cran_packages %>%
  filter(cum <= .975) %>%
  nrow()


ggplot(cran_packages, aes(x = rank, y = cum)) +
  geom_line(color = "#1892E3") +
  geom_vline(xintercept = n_975, lty = 3, color = "grey50") +
  geom_hline(yintercept = .975, lty = 3, color = "grey50") +
  theme_classic() +
  labs(
    title = "Distribution of packages by License tag",
    subtitle = paste("Extracted on", Sys.Date())
  ) +
  ylab("Distribution") +
  xlab("Licenses") +
  scale_y_continuous(labels = scales::percent_format())
```

Note that only `r n_975` Licenses string out or
`r nrow(cran_packages$n)` are used in
`r scales::percent(cran_packages[n_975, ]$cum, accuracy = 0.001)`
of the packages (`r prettyNum(sum(cran_packages[1:n_975, ]$n), big.mark = ",")` of
`r prettyNum(sum(cran_packages$n), big.mark = ",")`).


```{r}

# Copy DESCRIPTION of dplyr for manipulation

desc_file <- tempfile("DESCRIPTION_dplyr")


file.copy(
  file.path(find.package("dplyr"), "DESCRIPTION"),
  desc_file
)


cff_create(desc_file)["license"]

# Manipulate DESCRIPTION file

s <- desc::desc_set("License",
  cran_packages$cran_licenses[50],
  file = desc_file
)


cff_create(desc_file)["license"]
```

```{r}
# Check parser with licenses

lic <- cran_packages$cran_licenses
res <- c()
for (i in seq_len(length(lic))) {
  l <- desc::desc_set("License", lic[i], file = desc_file)
  r <- suppressMessages(cff_validate(cff_create(desc_file)))
  res <- c(res, r)
}

cran_packages$cff_is_valid <- res
```
```{r, results='asis',  echo=FALSE, message=TRUE}

errors <- cran_packages %>%
  filter(cff_is_valid == FALSE) %>%
  select(cran_licenses)

if (nrow(errors) == 0) {
  cat("\nAll the License strings have been parsed correctly.\n")
}
cat("\nThe following License strings has produced an error on parsing:\n")

cat(paste0("- ", cran_packages$cran_licenses, collapse = "\n"))
cat("\n")
```

## Mapping between Licenses used on CRAN packages and SPDX licenses

<details>
<summary>
<strong>Details</strong>
</summary>

```{r, echo=FALSE}
# Full mapping

mapping <- system.file("extdata/cran-to-spdx.csv", package = "cffr")

read.csv(mapping) %>% knitr::kable()
```

</details>
